---
title: "Practice I"
---

*(for the data merging lesson)*

(@) Import "genotypic_data_rotated.txt", "trial_data.csv", and "trial_metadata.csv"). 

(@) Do a full join between "trial_data" and "trial_metadata". 

(@) Do an inner join between "genotypic_data_rotated.txt" and "trial_data.csv"). 

(@) Do a semi-join of "genotypic_data_rotated" with "trial_data" and do the reverse. How does this compare with the inner join from the previous problem? 

(@) Do an anti-join between genotypic_data_rotated and trial_data. 

(@) Join together all common observations (by variety name) between the 3 files. 




.... why???
In the class project, there are two files with similar names in the "data" directory: 

### Main problem

* "genotypic_data.txt"
* "genotypic_data_rotated.txt"

As the file names indicates, "genotypic_data_rotated.txt" is a rotated version of "genotypic_data.txt".

Import  "genotypic_data.txt" into R and use R commands to recreate "genotypic_data_rotated.txt".


### Extra!

This is very much outside what has been taught, so only proceed if you don't mind a foray into the unknown. 

The column "individual" no longer has periods in the listed names, but the original file had periods in those names since they were column headers. Write code to remove those periods from the column "individual" in your transformed column (hint: look at the documentation for `gsub()`). 
