---
title: "Practice C"
---

(for lessons on data structures)

### Vectors

(@) You have this object in your R session: `x = 7`. What is the difference between `x[1]` and `x`?

(@) Make a vector of letters "a" to "m" (all lowercase) and letters "N" to "Z" (all uppercase).

(@) Make a vector of numbers 1 to 10 and 2 to 50. 

### Data Frames

(@) Make a data frame consisting of 6 rows and 4 columns, where one is a character variable, another is numeric, another is logical and the another is a factor. Verify that each column type is what you intended it to be. 

(@) You have this data frame:
```{r, eval=FALSE}
df <- data.frame(one = 1:10,
                 two = rnorm(10))
df$three <- df$two + rnorm(10)
df$four <- sample(c("A", "B"), 10, replace = TRUE)
```

* Add another column called 'five' that is a character variable consisting of levels that are fruits of your choice. 
* Add another column called 'six' that is 'five' coerced into a factor. 
* Make a new data frame with the columns in this order: "five", "one", "four", "two", "three". 


### Lists


(@)  You have this list: `mylist = list(x1 = "snow", x2 = 45:65, x3 = rep(letters[1:3], each = 3), x4 = matrix(1:100, nrow = 10))`. Return this list without x3. 

(@) Put all your vectors and the data frame from the previous problems in this exercise set into a list. For the first list item that has a vector, change the forth item of that vector to missing.

(@) For the list created in the previous problem, delete the second item. 

::: {.callout-tip collapse="true"}
## Hints
* the functions `letters()` and `LETTERS()` provide a shortcut for problem #3. 
* try using `NULL` for the last problem (under the "Lists" heading). 
:::

[***Solution***](../practice/solution-C.qmd)
