---
title: "Introductory R for Scientists"
subtitle: "Course Overview"
---

```{r echo=FALSE,include=FALSE}
library(quarto); library(here)
```

This workshop will take you from zero to hero over the course of 16 hours of instruction and practice. It will introduce the [R programming language](https://www.r-project.org/), the graphical user interface [RStudio](https://www.rstudio.com/products/rstudio/) and how R can be used to manage and analyse your data. At the end of this workshop, you will be able to:

-   import & export data
-   understand data types and object types
-   filter, reshape, merge and manipulate your data
-   mathematically transform data
-   do repeat actions in R
-   plot data
-   navigate R help files

### Who is This workshop for?

This workshop is intended for beginner R users. No previous experience in R or any other programming or statistical language is expected (although previous R users whose skills have lapsed are welcomed!)

### What this workshop will not cover

-   git, GitHub, or any version control
-   usage of the terminal (e.g. bash)
-   statistical analysis

### Requirements

* a computer with a reliable internet connection
* A camera and microphone for Zoom 
* A Zoom account (the free version is sufficient)

### When

Jan 17 - February 9\
Tuesday/Thursdays\
2 - 4 pm Pacific time

All sessions will take place over Zoom so students across different timezones can participate.

#### Office hours

I will hold open drop-in hours on Zoom on Wednesdays and Fridays, 1-2 pm if you have questions. It will be the same Zoom link for regular class sessions. 

### Instructors

#### Lead Instructor

[Julia Piaskowski](https://www.uidaho.edu/cals/statistical-programs/people/julia-piaskowski) | [training website](agstats.io) | [GitHub](https://github.com/jpiaskowski) | [personal website](https://jpiaskowski.gitlab.io/)


#### Teaching Assistants

[JT VanLeuven](https://www.uidaho.edu/cals/animal-veterinary-and-food-sciences/our-people/james-vanleuven) | [Research Website](https://sites.google.com/site/jtvanleuven/home)

[Breanna Sipley](https://sipley.github.io/) | [GitHub](https://github.com/sipley) | [Twitter](https://twitter.com/Breanna_Sipley)


