---
title: "Course Schedule"
---

*This schedule is best understood as a draft that will be adjusted as needed.* 


| Date            |   Topics          |       practice problems |
|-----------------|-------------------|-------------------------|
| Before January 17 | [Do Lesson Zero + Watch Video](lessons/Lesson00.qmd) |    |
| January 17 | Lesson 1: [math operators](lessons/Lesson01.qmd)\
                  Lesson 2: [vectorization](lessons/Lesson02.qmd) |  [*Lessons 1 & 2*](practice/practice-A.qmd) |
| January 19 | Lesson 4: [objects](lessons/Lesson04.qmd)\
                  Lesson 5: [data structures](lessons/Lesson05.qmd) |    [*Lesson 5*](practice/practice-B.qmd) \
                                                                          [*Lesson 6*](practice/practice-C.qmd)  |
| January 24 | Lesson 6: [R functions & help](lessons/Lesson06.qmd)\
               Lesson 7: [data import](lessons/Lesson07.qmd) \
               Lesson 8: [exporting data](lessons/Lesson08.qmd) | [*Lesson 7*](practice/practice-D.qmd) \
                                                                  [*Lesson 8*](practice/practice-E.qmd) |
| January 26   | Lesson 9: [data wrangling](lessons/Lesson09.qmd) |  [*Lesson 9*](practice/practice-F.qmd)  |
| January 31  | Lesson 10: [data aggregation & summary](lessons/Lesson10.qmd)\
                Lesson 11: [reshaping data sets](lessons/Lesson11.qmd) | [*Lesson 10*](practice/practice-G.qmd)\
                                     [*Lesson 11*](practice/practice-H.qmd) | 
| February 2  | Lesson 12: combining data sets \  
                Lesson 13: your R set-up |    |
| February 7  |  Lesson 15: ggplotting   |    |
| February 9  |  Lesson 15: ggplotting \
                 Final Lesson: Your R Future |    |
| extra  | Lesson 14: basic plotting \
              Lesson 16: repeating actions |   |


